# Catppuccin Mocha palette
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$username\
[](bg:peach fg:mauve)\
$directory\
[](fg:peach bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$nodejs\
$python\
$rust\
$golang\
[](fg:green bg:sapphire)\
$docker_context\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:mauve fg:crust"

[os.symbols]
Macos = " "

[username]
show_always = true
style_user = "bg:mauve fg:crust"
style_root = "bg:mauve fg:crust"
format = '[ $user ]($style)'

[directory]
style = "fg:crust bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"projects" = " "

[git_branch]
symbol = ""
style = "bg:yellow fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire fg:crust"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender fg:crust"
format = '[ ♥ $time ]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold yellow)'
